# Generated by Django 6.0.4 on 2026-04-13 04:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner_id',
            field=models.UUIDField(default=uuid.uuid7, editable=False),
        ),
    ]
