# Generated by Django 6.0.4 on 2026-04-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (4, 'In Progress'), (1, 'Done Usual'), (2, 'Done Fallback'), (3, 'Error')], default=0),
        ),
    ]
