# Generated by Django 6.0.4 on 2026-04-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_task_options_task_idx_task_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner_id', 'task_id'], name='idx_task_owner_task'),
        ),
    ]
